### PR TITLE
Location

### PR DESCRIPTION
**Pull request by DimitriosGkegkas**
Add the location handler. Now the location is passed as well the tracking data

### CODE REVIEW

**Comment by DimitriosGkegkas** [comment]
Once the previews bug fix request is merged I will rebase this branch in order to have a cleaner pull @chrispanag

**Comment by DimitriosGkegkas** [comment]
The rebase is completed @chrispanag

**Review by chrispanag — APPROVED** [review]

**Comment by chrispanag** [comment]
Tell me if it is ready for merging

**Comment by DimitriosGkegkas** [comment]
> Tell me if it is ready for merging

yes it is

**Pull request merged**
